Repository python-discord/bot-core, pull requests merged in 2022-07, with the labels that each got.

#105 Correctly determine source modules for re-exported symbols for docs
  docs/utils.py
Labels: a: documentation, t: enhancement

#101 Add `clean_text_or_reply` util.
  botcore/utils/__init__.py
  botcore/utils/commands.py
  docs/changelog.rst
Labels: a: code, t: feature

#107 Fix Docker Compose & Add Boilerplate Project
  .dockerignore
  .gitignore
  botcore/_bot.py
  dev/Dockerfile
  dev/README.rst
  dev/bot/__init__.py
  dev/bot/__main__.py
  dev/bot/cog.py
  dev/docker-compose.yaml
  docker-compose.yaml
  docs/changelog.rst
  docs/development.rst
  docs/index.rst
  poetry.lock
  pyproject.toml
  tox.ini
Labels: t: enhancement, a: other
